/**
 * AutoAgent Report Overlay
 *
 * Renders a scrollable markdown report generated by `autoagent report`.
 * Uses the pi Markdown component for full markdown rendering (tables, code,
 * headings, lists) inside box chrome with scroll support.
 *
 * Controls: ↑↓/j/k scroll, g/G top/end, Esc/Ctrl+C close.
 */

import type { Theme } from "@gsd/pi-coding-agent";
import { getMarkdownTheme } from "@gsd/pi-coding-agent";
import { Markdown, truncateToWidth, visibleWidth, matchesKey, Key } from "@gsd/pi-tui";

export class AutoagentReportOverlay {
  private tui: { requestRender: () => void };
  private theme: Theme;
  private onClose: () => void;
  private markdown: Markdown;
  private scrollOffset = 0;
  private cachedWidth?: number;
  private cachedLines?: string[];

  constructor(
    tui: { requestRender: () => void },
    theme: Theme,
    onClose: () => void,
    text: string,
  ) {
    this.tui = tui;
    this.theme = theme;
    this.onClose = onClose;

    const markdownTheme = getMarkdownTheme();
    this.markdown = new Markdown(text, 1, 1, markdownTheme);
  }

  handleInput(data: string): void {
    if (matchesKey(data, Key.escape) || matchesKey(data, Key.ctrl("c"))) {
      this.dispose();
      this.onClose();
      return;
    }

    if (matchesKey(data, Key.down) || matchesKey(data, "j")) {
      this.scrollOffset++;
      this.invalidate();
      this.tui.requestRender();
      return;
    }

    if (matchesKey(data, Key.up) || matchesKey(data, "k")) {
      this.scrollOffset = Math.max(0, this.scrollOffset - 1);
      this.invalidate();
      this.tui.requestRender();
      return;
    }

    if (data === "g") {
      this.scrollOffset = 0;
      this.invalidate();
      this.tui.requestRender();
      return;
    }

    if (data === "G") {
      this.scrollOffset = 999;
      this.invalidate();
      this.tui.requestRender();
      return;
    }
  }

  render(width: number): string[] {
    if (this.cachedLines && this.cachedWidth === width) {
      return this.cachedLines;
    }

    const innerWidth = width - 4; // box chrome: │ + space on each side
    const content = this.markdown.render(innerWidth);

    const viewportHeight = Math.max(5, process.stdout.rows ? process.stdout.rows - 8 : 24);
    const chromeHeight = 2; // top + bottom border
    const visibleContentRows = Math.max(1, viewportHeight - chromeHeight);
    const maxScroll = Math.max(0, content.length - visibleContentRows);
    this.scrollOffset = Math.min(this.scrollOffset, maxScroll);
    const visibleContent = content.slice(this.scrollOffset, this.scrollOffset + visibleContentRows);

    const lines = this.wrapInBox(visibleContent, width);

    this.cachedWidth = width;
    this.cachedLines = lines;
    return lines;
  }

  private wrapInBox(inner: string[], width: number): string[] {
    const th = this.theme;
    const border = (s: string) => th.fg("borderAccent", s);
    const innerWidth = width - 4;
    const lines: string[] = [];

    // Title bar
    const title = th.fg("accent", th.bold(" AutoAgent Report "));
    const titleVis = visibleWidth(title);
    const leftDash = Math.max(1, Math.floor((width - 2 - titleVis) / 2));
    const rightDash = Math.max(1, width - 2 - leftDash - titleVis);
    lines.push(border("╭" + "─".repeat(leftDash)) + title + border("─".repeat(rightDash) + "╮"));

    for (const line of inner) {
      const truncated = truncateToWidth(line, innerWidth);
      const padWidth = Math.max(0, innerWidth - visibleWidth(truncated));
      lines.push(border("│") + " " + truncated + " ".repeat(padWidth) + " " + border("│"));
    }

    // Footer hint
    const hint = th.fg("dim", " ↑↓ scroll · g/G top/end · esc close ");
    const hintVis = visibleWidth(hint);
    const hLeftDash = Math.max(1, Math.floor((width - 2 - hintVis) / 2));
    const hRightDash = Math.max(1, width - 2 - hLeftDash - hintVis);
    lines.push(border("╰" + "─".repeat(hLeftDash)) + hint + border("─".repeat(hRightDash) + "╯"));

    return lines;
  }

  private invalidate(): void {
    this.cachedWidth = undefined;
    this.cachedLines = undefined;
  }

  dispose(): void {
    // No timers or subscriptions to clean up — report is static content
  }
}
